### PR TITLE
Fix signup

### LINKED ISSUE #372: Activity: Notice: undefined variable
When not logged in and viewing an activity that has a form, I get the following notice:
```
Notice
: Undefined variable: form in
C:\xampp\htdocs\gewisweb\module\Activity\src\Activity\Controller\ActivityController.php
on line
59
```

### LINKED ISSUE #373: Activity: Not added to table after subscription
When you subscribe to an activity, you do not show up in the table. After a refresh, you *are* in the table.

### LINKED ISSUE #374: Activity: success is not set on successful signoff
The success alert is never shown because success is not set

### LINKED ISSUE #375: Activity: CSRF vulnerability on activity signoff
You do not need to use the form to signoff for an activity. It should not be possible to signoff by only requesting an url like `/gewisweb/public/activity/signoff/9`.

### PR DESCRIPTION
**Pull request by mstruijs**
Fixes several bugs related to the signup process for activities:

- Define the undefined variables in the views (fixes #372 )
- Provide the proper ACL rights
- Make sure that the order of the persons that subscribed for the activity is displayed correctly.
- Fix some bugs in the controller (fixes #374 )
- Ensure that the subscription table is updated immediately (fixes #373 )
- Use a form for unsubscribing (fixes #375 )

### CODE REVIEW

File: module/Activity/src/Activity/Service/Signup.php [hunk 1]
```diff
@@ -87,10 +87,14 @@ public function getSignedUpData(ActivityModel $activity)
...
 
         $fieldValueMapper = $this->getServiceManager()->get('activity_mapper_activity_field_value');
+        $memberMapper = $this->getServiceManager()->get('decision_mapper_member');
         $result = [];
         foreach($activity->getSignUps() as $signup){
             $entry = [];
-            $entry['member'] = $signup->getUser()->getMember()->getFullName();
+            //$signup->getUser()->getMember() yields an empty result if the signup is new.
+            //(i.e. a signup has taken place in the same request)
+            $member = $memberMapper->findByLidnr($signup->getUser()->getLidnr());
```
Comment (mstruijs) [inline module/Activity/src/Activity/Service/Signup.php]: Since `$signup->getUser()->getMember()` gets a doctrine proxy object (`DoctrineORMModule\Proxy\__CG__\Decision\Model\Member`), filled with null-values if the signup has been created in the same request, I have used a different way to get the name. I don't know enough about Doctrine to either tell if this a symptom of another bug or how to properly do this. This way does seem to work, though.

File: module/Activity/src/Activity/Controller/ActivityController.php [hunk 2]
```diff
@@ -7,6 +7,7 @@
 use Zend\Mvc\Controller\AbstractActionController;
 use Zend\Session\Container as SessionContainer;
 use Activity\Form\ActivitySignup as SignupForm;
+use Activity\Form\ModifyRequest as RequestForm;
```
Comment (jszanto) [inline module/Activity/src/Activity/Controller/ActivityController.php]: This form does not seem to exist? Also it is better to retrieve new form instances from the service using the service manager. (To allow easy passing of constructors for translation, etc.)

File: module/Activity/src/Activity/Service/Signup.php (hunk 1 above)
Comment (jszanto) [inline module/Activity/src/Activity/Service/Signup.php]: I can't quite produce any issues when I try replacing that by $signup->getUser()->getMember() again.

File: module/Activity/src/Activity/Controller/ActivityController.php (hunk 2 above)
Comment (mstruijs) [inline module/Activity/src/Activity/Controller/ActivityController.php]: It seems I had forgotten to add it. Retrieving form instances from the service is a good idea in general, but does not benefit this particular form (no instances living in the service are required) and this has not been applied yet in the rest of the module, so I think that that can be deferred.

File: module/Activity/src/Activity/Service/Signup.php (hunk 1 above)
Comment (mstruijs) [inline module/Activity/src/Activity/Service/Signup.php]: I cannot reproduce the issues I got myself either. Which version should be kept? ('either one' is a valid answer)

Comment (jszanto) [inline module/Activity/src/Activity/Service/Signup.php]: I think the previous version is better (and it saves a database query)

**Comment by jszanto** [comment]
Also note that this branch has some merge conflicts.
