### PR TITLE
Fixes uploading a banner when editing a company and when editing a banner package

### LINKED ISSUE #365: Bedrijven: uploading banner does not work when editing a banner package

### PR DESCRIPTION
**Pull request by wsinnema**
Fixes #365 and #364

### CODE REVIEW

File: module/Company/src/Company/Service/Company.php [hunk 1]
```diff
@@ -56,12 +56,25 @@ public function getHiddenCompanyList()
...
+                $package->exchangeArray($data);
+                $file = $files['banner'];
+                try {
+                    $oldPath = $package->getImage();
+                    $newPath = $this->getFileStorageService()->storeUploadedFile($file);
+                    $package->setImage($newPath);
+                    if ($oldPath != '' && oldPath != newPath) {
+                        $this->getFileStorageService()->removeFile($oldPath);
+                    }
+                } catch (\Exception $exception) {
```
Comment (kokx) [inline module/Company/src/Company/Service/Company.php]: Why an empty catch block? This is really bad practise. Also, catch statements that catch all exceptions are bad as well. Please try to catch less here.

Comment (jszanto) [inline module/Company/src/Company/Service/Company.php]: It might be better to fix this in #367 and then rebase your other branches once that PR is merged. Now we have this same issue in 3 of your PRs.

Comment (wsinnema) [inline module/Company/src/Company/Service/Company.php]: I need to catch an \Exception here. Sure, I could rewrite this part to check for the error condition too, but that would result in code duplication, which is also bad practise.

Comment (wsinnema) [inline module/Company/src/Company/Service/Company.php]: Everything is fixed now
