### PR TITLE
Fixes bug  that gave error when editing a company

### LINKED ISSUE #572: Company: companies can't be edited without changing the slugname
When editing a company the input is invalid because the slug name exists already.

### PR DESCRIPTION
**Pull request by wsinnema**
Fixes #572

### CODE REVIEW

File: module/Company/src/Company/Form/EditCompany.php [hunk 1]
```diff
@@ -326,4 +328,19 @@ protected function initFilters($mapper)
...
     }
+    public function slugNameUnique($slugName, $context)
+    {
+        $objects = $this->mapper->findEditableCompaniesBySlugName($slugName, true);
+        $cid = $context['id'] ;
+        foreach ($objects as $company) {
+            if ($company->getID() != $cid) {
+                echo $cid;
+                echo $company->getID();
+
```
Comment (jszanto) [inline module/Company/src/Company/Form/EditCompany.php]: This looks like debug code

Comment (wsinnema) [inline module/Company/src/Company/Form/EditCompany.php]: It's removed now
