### PR TITLE
Redesign of Activity module

### LINKED ISSUE #235: Link dinner options to activities

### LINKED ISSUE #598: Activity: Additional fields are not translated.
If a field of an activity is requested in a language, but only available in the other, the field should be presented in the other language. However, this currently fails for the additional fields of an activity.

### LINKED ISSUE #668: Subscription start date
Add the ability to set a date on which the subscriptions for an activity start

### LINKED ISSUE #728: Activity: Allow changing options in certain cases.
It is generally not possible to change options of activities, due to the problems that arise with already subscribed members. 

However, it is useful to be able to change/add/remove options when 1) the activity has not been approved and 2) no-one has been subscribed to the activity. 

Enable this functionality in the described case.

### LINKED ISSUE #749: Activity categories

### LINKED ISSUE #801: Language fallback for activities
Provide some sort of easy fallback mechanism when one of the languages for an activity is missing instead of the hacky methods we currently have for this.

### LINKED ISSUE #844: Incorrect form validation on Choice field with one language disabled
- Create an activity with Dutch disabled and English enabled.
- Add a Choice field with some options and try to submit the form.
- ???
- "The number of English options must equal the number of Dutch options"

image

### LINKED ISSUE #1012: ACL privileges in the Activity module are broken
Certain privileges in the `activity_acl` do not work/are not granted to certain roles.

1) `user` is granted activity creation privileges. However, they are unable to create activities as they are greeted by an internal server error.
https://github.com/GEWIS/gewisweb/blob/96761abc6194d6f798e7b96a12b2d4a56400400b/module/Activity/Module.php#L180
This is because `user` must be able to edit organs to be allowed to view the activity creation form.
https://github.com/GEWIS/gewisweb/blob/96761abc6194d6f798e7b96a12b2d4a56400400b/module/Decision/src/Decision/Service/Organ.php#L59-L63
Which it does not have:
https://github.com/GEWIS/gewisweb/blob/96761abc6194d6f798e7b96a12b2d4a56400400b/module/Decision/Module.php#L147-L150

2) `user` and `active_user` are not given their proper privileges due to internal checks.
https://github.com/GEWIS/gewisweb/blob/96761abc6194d6f798e7b96a12b2d4a56400400b/module/Activity/Module.php#L185-L191
This is because the `IsCreator()` and `IsOrganMember` assertions check if the `ResourceInterface` is of the proper type. This is not the case as `activity` (second parameter in `allow()`) is a `GenericResource` and not `CreatorResourceInterface` or `OrganResourceInterface`.
https://github.com/GEWIS/gewisweb/blob/96761abc6194d6f798e7b96a12b2d4a56400400b/module/User/src/User/Permissions/Assertion/IsCreator.php#L39-L41
https://github.com/GEWIS/gewisweb/blob/96761abc6194d6f798e7b96a12b2d4a56400400b/module/User/src/User/Permissions/Assertion/IsOrganMember.php#L41-L43

3) Due to the above-mentioned check failing another issue has never been resolved in one of the assertions (except for `isCurrentBoard` in 960aea9eb547aed18b9645a9f6d91873a3140884). `getDischargeDate` is a function and not a variable.
https://github.com/GEWIS/gewisweb/blob/96761abc6194d6f798e7b96a12b2d4a56400400b/module/User/src/User/Permissions/Assertion/IsOrganMember.php#L73

### LINKED ISSUE #1041: Allow for Company activities
Jealy/C4 had the idea to couple activities to companies. This would suitable for some career activities.
Then you could also have an overview for solely external activities.

### PR DESCRIPTION
**Pull request by tomudding**
This is a WIP PR for the changes proposed on the [wiki](https://github.com/gewis/gewisweb/wiki/Activity-Redesign) related to the redesign of the Activity module. This will become the central place to keep track of what is already done and what still has to be done.

## Roadmap ([wiki](https://github.com/gewis/gewisweb/wiki/Activity-Redesign))
- [X] Remove the old activity translation code and replace them with `LocalisedText`.
- [ ] Create an interface for activity creation/deletion as described in the '[CRUD](https://github.com/gewis/gewisweb/wiki/Activity-Redesign#crud)' section.
- [X] Split `Activity` into `Activity` and `SignupList`.
- [X] Add the activity categories.
- [X] Create the option for multiple `SignupList`s.
- [ ] Create Doctrine Migrations procedure to get the old data in the new format.

## Planned Changes
- [X] #235 - Link dinner options to activities (as part of `SignupList`s).
- [X] #598 - Activity: Additional fields are not translated.
- [X] #668 - Subscription start date
- [X] #728 - Activity: Allow changing options in certain cases.
- [X] #749 - Activity categories
- [X] #801 - Language fallback for activities
- [X] #844 - Incorrect form validation on Choice field with one language disabled
- [X] #1012 - ACL privileges in the Activity module are broken
- [X] #1041 - Allow for Company activities

## Implemented Changes / Fixes
This PR currently fixes several issues, namely; fixes #235, fixes #598, fixes #668, fixes #728, fixes #749, fixes #801, fixes #844, fixes #1012, and fixes #1041.

### CODE REVIEW

**Comment by tomudding** [comment]
a771b34 fixes #844.

**Comment by tomudding** [comment]
Activities are no longer activities, they are now Activities and SignupLists.

This change brings a lot of good things, however, there are currently some issues. First and foremost, updating activities does not work. I am not sure why. Secondly, there is a lot of legacy code / documentation that I have not yet changed and/or removed.

File: module/Activity/src/Activity/Controller/AdminCategoryController.php [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+        $categoryService = $this->getServiceLocator()->get('activity_service_category');
+        $form = $categoryService->getCategoryForm();
+        $request = $this->getRequest();
+        $translator = $this->getServiceLocator()->get('translator');
+
+        if ($request->isPost()) {
+            $form->setData($request->getPost());
+
+            if ($form->isValid()) {
+                $category = $categoryService->createCategory($form->getData());
```
Comment (kokx) [inline module/Activity/src/Activity/Controller/AdminCategoryController.php:36]: Why not handle the form in the category service, as is customary in the rest of the code base?

File: module/Activity/src/Activity/Controller/AdminCategoryController.php [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+
+            if ($form->isValid()) {
+                $category = $categoryService->updateCategory($category, $form->getData());
+
+                if ($category instanceof \Activity\Model\ActivityCategory) {
+                    $message = $translator->translate('The activity category was successfully updated!');
+
+                    return $this->redirectWithNotice(true, $message);
+                }
+            }
```
Comment (kokx) [inline module/Activity/src/Activity/Controller/AdminCategoryController.php:101]: Same here, why not handle the form in the category service?

**Review by kokx — COMMENTED** [review]
Just a few things I saw in passing.

File: module/Activity/src/Activity/Controller/AdminCategoryController.php (hunk 2 above)
Comment (jszanto) [reply module/Activity/src/Activity/Controller/AdminCategoryController.php:101]: Putting this in the service would also allow you to structure it a bit nicer without nested if statements.

**Review by jszanto — COMMENTED** [review]
Didn't have time to look at everything yet, but looks like this is going in the right direction.

File: module/Activity/src/Activity/Form/Activity.php [hunk 3]
```diff
@@ -227,34 +193,54 @@ public function __construct(array $organs, Translator $translator, ObjectManager
...
     {
         $valid = parent::isValid();
-
         /*
          * This might seem like a bit of a hack, but this is probably the only way zend framework
          * allows us to do this.
+         *
+         * TODO: Move this to an actual InputFilter to add messages, because
+         * marking inputs as invalid (and adding messages) cannot be done from
+         * this function.
```
[the remark this answers is not in the document]
Comment (tomudding) [reply module/Activity/src/Activity/Form/Activity.php:202]: From what I can tell from the Zend documentation this is only possible with an actual `InputFilter`, as in the `Form`/`FieldSet` you cannot add error messages. As the documentation is a bit sparse in that regard I have not figured out how this should work in practice, as the the `Activity` form is actually 3 separate forms.

File: module/Activity/src/Activity/Controller/AdminCategoryController.php (hunk 2 above)
Comment (tomudding) [reply module/Activity/src/Activity/Controller/AdminCategoryController.php:101]: Thanks for the feedback! I have no idea why I started doing it in this way, because - as you mentioned - everywhere else we do not use this particular "method".

Comment (tomudding) [reply module/Activity/src/Activity/Controller/AdminCategoryController.php]: @kokx I have changed these two occurrences, however, I think some of the older parts of the Activity module also need to be changed to reflect this.

In the meantime I also found out why I started using this specific structure. In the Zend 2 documentation the above is used for all form (validation) examples. It is most probable that I unconsciously started doing the same thing.

**Comment by tomudding** [comment]
Currently an update proposal to an activity _cannot_ change the sign-up lists. However, the idea of #728 is that this will be possible in certain cases: the activity has not been approved **and** there are no sign-ups in any of the sign-up lists.

- [ ] To allow this the `orphanRemoval` should be changed to `cascade="remove"` and the logic in [`Activity\Service\Activity:copyActivity()`](https://github.com/GEWIS/gewisweb/blob/f4c74196f91c4d6cb37bf873e9cfc6c189c19349/module/Activity/src/Activity/Service/Activity.php#L289-L314) should be adapted to make this possible:
https://github.com/GEWIS/gewisweb/blob/f4c74196f91c4d6cb37bf873e9cfc6c189c19349/module/Activity/src/Activity/Model/Activity.php#L116-L121

One note on the activity approval and update proposal approval views, the description is shown as text and not formatted according to the markdown code. The approver can still see the formatted text on the activity's page.

- [ ] "Signup List(s)" is incorrect and should be changed to "Sign-up List(s)".

File: module/Activity/src/Activity/Service/Activity.php [hunk 4]
```diff
@@ -119,346 +342,347 @@ private function requestGEFLITST($activity, $user, $organ)
...
+        $difference = [];
+
+        foreach ($array1 as $key => $value) {
+            if (is_array($value)) {
+                if (!array_key_exists($key, $array2) || !is_array($array2[$key])) {
+                    $difference[$key] = $value;
+                } else {
+                    $newDifference = $this->array_diff_assoc_recursive($value, $array2[$key]);
+
+                    if (!empty($new_diff)) {
```
Comment (Koen1999) [inline module/Activity/src/Activity/Service/Activity.php:572]: I think new_diff is undefined. Shoudln't this be newDifference?
This seems like a bug,

File: module/Activity/src/Activity/Controller/AdminApprovalController.php [hunk 5]
```diff
@@ -47,7 +22,17 @@ public function viewAction()
         $id = (int) $this->params('id');
         $queryService = $this->getServiceLocator()->get('activity_service_activityQuery');
 
-        /** @var $activity Activity*/
+        $acl = $translator = $this->getServiceLocator()->get('activity_acl');
```
Comment (Koen1999) [inline module/Activity/src/Activity/Controller/AdminApprovalController.php:25]: $acl = $translator = $this.... ?
This seems like a bug as well.
Try assigning either to $acl or $translator

File: module/Activity/src/Activity/Controller/AdminController.php [hunk 6]
```diff
@@ -2,206 +2,302 @@
...
+
+            $result['externalSignupForm'] = $externalSignupForm;
+            $result['externalSignoffForm'] = new RequestForm(
+                'activityExternalSignoff',
+                $this->getServiceLocator()->get('translator')->translate('Remove')
+            );
+        }
 
-        $activityService = $this->getServiceLocator()->get('activity_service_activity');
         $signupService = $this->getServiceLocator()->get('activity_service_signup');
```
Comment (Koen1999) [inline module/Activity/src/Activity/Controller/AdminController.php:225]: This variable $signupService is never used. Consider removing it or use it

File: module/Activity/src/Activity/Service/Signup.php [hunk 7]
```diff
@@ -355,23 +411,36 @@ public function isAllowedToSubscribe()
...
+        return $this->isAllowed('externalSignup', 'signupList');
     }
 
     public function isAllowedToViewSubscriptions()
     {
-        return $this->isAllowed('view', 'activitySignup');
+        return $this->isAllowed('view', 'signupList');
     }
 
     public function isAllowedToInternalSubscribe()
```
Comment (Koen1999) [inline module/Activity/src/Activity/Service/Signup.php:422]: This method does exactly the same as isAllowedToSubscribe() on line 402.
Moreover, why do we need functions for performing this check since it is just one line of code?

Comment (Koen1999) [reply module/Activity/src/Activity/Service/Signup.php:422]: Last comment also holds for other isAllowedToFoo methods

File: module/Activity/src/Activity/Form/SignupList.php [hunk 8]
```diff
@@ -0,0 +1,230 @@
...
+                            'encoding' => 'UTF-8',
+                            'min' => 1,
+                            'max' => 100,
+                        ],
+                    ],
+                ],
+            ],
+            'openDate' => [
+                'required' => true,
+                // TODO: Move to an actual InputFilter
```
Comment (Koen1999) [inline module/Activity/src/Activity/Form/SignupList.php:150]: Should we leave these huge TODO blocks in?

File: module/Activity/view/activity/admin-category/add.phtml [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+                <hr>
+            </div>
+            <div class="col-md-12">
+                <?php
+                $name = $form->get('name')
+                    ->setAttribute('disabled', 'disabled')
+                    ->setAttribute('class', 'form-control form-control-dutch')
+                    ->setAttribute('id', 'name-nl');
+                $nameValue = $name->getValue();
+                $name->setValue(is_null($nameValue) ? '' : (is_string($nameValue) ? $nameValue : $nameValue->getValueNL()));
```
Comment (Koen1999) [inline module/Activity/view/activity/admin-category/add.phtml:41]: Can we simplify this experssion?
Perhaps use another variable

Comment (Koen1999) [reply module/Activity/view/activity/admin-category/add.phtml:41]: There are quite some similar statements for which I would like to make the same suggestion.

File: module/Activity/view/activity/admin/participants.phtml [hunk 10]
```diff
@@ -1,34 +1,72 @@
...
+</div>
+<?php if (isset($signupLists)): ?>
+    <div class="row">
+        <div class="col-md-12">
+            <ul class="nav nav-tabs">
+                <li role="presentation" <?= isset($signupList) ? '' : 'class="active"' ?>>
+                    <a href="<?= $this->url('activity_admin/participants', ['id' => $activity->getId()]) ?>"><?= $this->translate('General') ?></a>
+                </li>
+                <?php foreach ($signupLists as $list): ?>
+                    <li role="presentation" <?= isset($signupList) ? ($signupList->getId() === $list['id'] ? 'class="active"' : '') : '' ?>>
```
Comment (Koen1999) [inline module/Activity/view/activity/admin/participants.phtml:29]: Can we also simplify this expression?
Perhaps by using an extra variable

File: module/Activity/view/activity/activity/view.phtml [hunk 11]
```diff
@@ -1,254 +1,296 @@
...
+        </div>
+        <?php if (isset($signupLists)): ?>
+            <div class="row">
+                <div class="col-md-12">
+                    <h2><?= $this->translate('Sign-up Lists') ?></h2>
+                </div>
+                <div class="col-md-12">
+                    <ul class="nav nav-tabs">
+                        <?php foreach ($signupLists as $list): ?>
+                            <li role="presentation" <?= isset($signupList) ? ($signupList->getId() === $list['id'] ? 'class="active"' : '') : '' ?>>
```
Comment (Koen1999) [inline module/Activity/view/activity/activity/view.phtml:117]: Can we also simplify this expression?

File: module/Activity/src/Activity/Controller/ActivityController.php [hunk 12]
```diff
@@ -131,223 +168,246 @@ protected function prepareSignupForm($fields, & $activitySession, & $externalSes
...
+            'form' => $form,
+            'action' => $translator->translate('Create Activity'),
+            'allowSignupList' => true,
+        ];
     }
 
     /**
      * Signup for a activity.
      */
     public function signupAction()
```
Comment (Koen1999) [inline module/Activity/src/Activity/Controller/ActivityController.php:195]: The signupAction has lots of similarities with the externalSignupAction. Both functions are quite complex as well. Do you think it is possible to extract some common functionalities to seperate method(s)?

**Review by Koen1999 — CHANGES_REQUESTED** [review]
Overall the code looks alright. I do however suggest some changes.
Refer to the comments I left in this review.

Additionally these are some code climate issues that are worth fixing: 
afbeelding

Last but not least, I propose some code quality/formatting/climate changes (of which not all relate to this PR; but they all do relate to the activity module). I recommend reviewing/adjusting/merging this PR before making other changes: https://github.com/GEWIS/gewisweb/pull/1067

File: module/Activity/view/activity/admin-category/add.phtml (hunk 9 above)
Comment (tomudding) [reply module/Activity/view/activity/admin-category/add.phtml:41]: I will make it a view helper to clean up the nested ternary operators.

**Review by Koen1999 — APPROVED** [review]
This is functional. Only requires a migration procedure, but Tom is working on that. This can be merged in my opinion.
