### PR TITLE
Fix being unable to set profile photo from photo viewer

### LINKED ISSUE #1338: Cannot set profile photo in the new photo viewer
As reported by Jelmer, there is currently no button to set a photo as your profile photo. We should add a button in the menu bar which can be used to set a photo (in which you have been tagged) as your profile photo.

### PR DESCRIPTION
**Pull request by tomudding**
Fixes #1338.

**After:**
image

### CODE REVIEW

File: module/Photo/src/Service/Photo.php [hunk 1]
```diff
@@ -575,6 +575,7 @@ private function storeProfilePhoto(
      */
     public function setProfilePhoto(int $photoId): void
     {
+        // TODO: Add null check for `$photo`.
```
Comment (Koen1999) [inline module/Photo/src/Service/Photo.php:578]: This TODO mark should either be addressed or removed if it is not necessary.

Comment (tomudding) [reply module/Photo/src/Service/Photo.php:578]: It should definitely be done at some point, but I don't want to do it now. I'll make an issue for it and remove it from this PR.

Comment (Koen1999) [reply module/Photo/src/Service/Photo.php]: Alright, sounds good too.

**Review by Koen1999 — APPROVED** [review]
