### PR TITLE
Fix calling `getApprover()` on non-existent poll

### LINKED ISSUE #1343: Viewing non-existent poll results in unhandled operations on `null` object
```
[2022-01-29T00:21:56.821523+01:00] gewisweb.ERROR: Error: Call to a member function getApprover() on null in /code/module/Frontpage/src/Service/Poll.php:101 Stack trace:
#0 /code/module/Frontpage/src/Controller/PollController.php(98): Frontpage\Service\Poll->getPoll(537)
#1 /code/module/Frontpage/src/Controller/PollController.php(66): Frontpage\Controller\PollController->obtainPoll()
#2 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Frontpage\Controller\PollController->indexAction()
#3 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#4 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#5 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#6 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#7 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /code/public/index.php(20): Laminas\Mvc\Application->run() 
#11 {main} [] []
```

### PR DESCRIPTION
**Pull request by tomudding**
Fixes #1343. Also contains a small refactor of the `PollAdminController`.

### CODE REVIEW

File: module/Frontpage/src/Controller/PollAdminController.php [hunk 1]
```diff
@@ -57,30 +80,52 @@ public function listAction(): ViewModel
...
             $poll = $this->pollService->getPoll($pollId);
-            $this->pollService->approvePoll($poll, $this->getRequest()->getPost());
 
-            return $this->redirect()->toRoute('admin_poll');
+            if (null !== $poll) {
+                $approvalForm = $this->pollService->getPollApprovalForm();
+                $approvalForm->bind($poll);
+                $approvalForm->setData($this->getRequest()->getPost()->toArray());
+
+                if ($approvalForm->isValid()) {
```
Comment (Koen1999) [inline module/Frontpage/src/Controller/PollAdminController.php:98]: Why is this validation necessary? And have you tested the changes?

**Review by Koen1999 — APPROVED** [review]
Nice to see that you moved the ACL checks from the service to the controller!

File: module/Frontpage/src/Controller/PollAdminController.php (hunk 1 above)
Comment (tomudding) [reply module/Frontpage/src/Controller/PollAdminController.php:98]: It is to validate the expiry date, there is not really a reason to actually `bind` the model but I just moved the code from the service (and it still works).
